
#theme: minimal-mistakes-jekyll
# 第三方开源主题
remote_theme: "mmistakes/minimal-mistakes"


title: 'Simple is better'
logo: "/assets/logo.png"

encoding: "utf-8"
permalink: /:categories/:title/

plugins:
  - jekyll-include-cache

# 设定默认的布局
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      classes: wide
      read_time: true