
#theme: minimal-mistakes-jekyll
# 第三方开源主题
remote_theme: "mmistakes/minimal-mistakes"


title: '也无风雨也无晴'
logo: "/assets/logo2.png"

encoding: "utf-8"
permalink: /:categories/:title/
#search: true
markdown: GFM

author:
  #name: "near"
  avatar: "/assets/actor2.jpg"
  bio: "LESS IS MORE" # Note: Markdown is allowed
  location: "成都"

plugins:
  - jekyll-include-cache



# 设定默认的布局
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      classes: wide      